name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: read

jobs:
  test-publish:
    name: Publish to TestPyPI
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/mhz14a

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install build dependencies
      run: python -m pip install --upgrade pip build

    - name: Build package
      run: python -m build

    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: test-publish
    environment:
      name: pypi
      url: https://pypi.org/p/mhz14a

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install build dependencies
      run: python -m pip install --upgrade pip build

    - name: Build package
      run: python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
